version: '3.8'

services:
  ozon:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - static_volume:/code/static
    expose:
      - 8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - static_volume:/code/static
    ports:
      - 8085:8085
    depends_on:
      - ozon

  redis:
    image: redis:alpine

  db:
    image: 'postgres:latest'
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: shop_product
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5432:5432"


  celery:
    build:
      context: .
    command: celery -A config worker -l info
    volumes:
      - static_volume:/code/static
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
    command: celery -A config beat -l info
    volumes:
      - static_volume:/code/static
    depends_on:
      - redis

volumes:
  pgdata:
  static_volume:
