# Generated by Django 4.1.6 on 2023-02-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='posting_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
