# Generated by Django 4.1.6 on 2023-02-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='shop.warehouse'),
        ),
    ]
