# Generated by Django 4.1.6 on 2023-02-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_number', to='shop.warehouse')),
            ],
        ),
    ]
