# Generated by Django 4.1.6 on 2023-04-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_articlenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
    ]
